name: Run Python script every 6 hours or on push to master

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok jq

    - name: Start ngrok
      run: |
        nohup ngrok http 5000 --log=stdout > ngrok.log &
      env:
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

    - name: Wait for ngrok to start
      run: sleep 5

    - name: Get ngrok URL
      id: get-ngrok-url
      run: |
        NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV

    - name: Display ngrok URL
      run: echo "ngrok URL: ${{ env.NGROK_URL }}"

    - name: Run Python script
      run: python app.py